plugins:
  - babel
  - jest
  - react

extends:
  - airbnb-base
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  class-methods-use-this: 0
  max-len: [2, 144, 4, {"ignoreUrls": true}]
  no-restricted-syntax: ["error", "ForInStatement", "LabeledStatement", "WithStatement"]

settings:
  react:
    version: "16.13"
